[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers --alluredir=reports/allure-results --clean-alluredir
markers =
    smoke: 冒烟测试
    user: 用户模块测试
    address: 收货地址模块测试

# 禁用 Unicode 转义，正确显示中文用例名
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
